set str "this is a string"
puts "the string is:$str"
puts "the length of string is:[string length $str]"
puts "the character at index 3 is:[string index $str 3]"
puts "the characters from index 4 through 8 are:[string range $str 4 8]"
puts "the index of the 1st occurence of letter\"i\" is:[string first i $str]"
